#!/usr/bin/env python3
"""
Claude Code memory kit updater.
Safely updates the kit portions of your project without touching your project-specific content.

What it updates:
  CLAUDE.md          — session commands block only (## Session Commands → ## If Your Session Crashes)
  setup.py           — full replacement
  tools/check_memory.py — full replacement

What it never touches:
  .claude/memory/    — all your memory files
  STATUS.md          — your session log
  Everything below ## What This Project Is in CLAUDE.md

Supported CLAUDE.md heading styles:
  ## Session Commands   — standard (generated by setup.py)
  ## Quick Commands     — recognized fallback
  ## Commands           — recognized fallback

Usage:
  python update.py                                       # fetch latest from default GitHub repo
  python update.py https://github.com/user/repo         # fetch from a specific GitHub repo or fork
  python update.py https://github.com/user/repo/tree/branch  # fetch from a specific branch
  python update.py /path/to/starter/kit                 # use a local copy of the kit (no internet)
"""

import re
import subprocess
import sys
from pathlib import Path


def _detect_python_bin():
    """Detect whether python3 or python is the right binary on this machine."""
    for candidate in ("python3", "python"):
        try:
            r = subprocess.run([candidate, "--version"], capture_output=True, timeout=5)
            if r.returncode == 0:
                return candidate
        except Exception:
            pass
    return "python"

DEFAULT_GITHUB_BASE = "https://raw.githubusercontent.com/YehudaFrankel/clankbrain/main"
ROOT                = Path.cwd()

# Alternative heading names the updater recognizes, in priority order.
# Each entry: (heading_text, fallback_label_or_None)
# fallback_label is None for the standard heading (no note shown).
# For alternatives, fallback_label is the heading string (shown in the note).
_KNOWN_START_HEADINGS = [
    ("## Session Commands", None),
    ("## Quick Commands",   "## Quick Commands"),
    ("## Commands",         "## Commands"),
]


def github_url_to_raw_base(url):
    """Convert a github.com repo URL to a raw.githubusercontent.com base URL.

    Handles:
      https://github.com/user/repo                → raw base at /main
      https://github.com/user/repo/tree/branch    → raw base at /branch
    """
    url = url.rstrip("/")
    m = re.search(r"github\.com/([^/]+/[^/]+)(?:/tree/(.+))?$", url)
    if not m:
        return None, f"Could not parse GitHub URL: {url}"
    repo   = m.group(1)
    branch = m.group(2) or "main"
    return f"https://raw.githubusercontent.com/{repo}/{branch}", None


def get_content(source, rel_path, github_base=None):
    """Fetch file content from GitHub or a local kit folder."""
    if source == "github":
        import urllib.request
        base = github_base or DEFAULT_GITHUB_BASE
        url  = f"{base}/{rel_path}"
        try:
            with urllib.request.urlopen(url, timeout=10) as resp:
                return resp.read().decode("utf-8")
        except Exception as e:
            print(f"  ERROR fetching {rel_path} from {base}: {e}")
            return None
    else:
        p = Path(source) / rel_path
        if p.exists():
            return p.read_text(encoding="utf-8")
        print(f"  ERROR: Not found: {p}")
        return None


def extract_kit_block(text):
    """
    Extract the kit-managed block from a CLAUDE.md:
    from '## Session Commands' through the end of '## If Your Session Crashes'
    (stops before the next --- separator)
    """
    m_start = re.search(r'^## Session Commands', text, re.MULTILINE)
    if not m_start:
        return None, "Could not find '## Session Commands' in kit CLAUDE.md"

    m_end = re.search(
        r'^## If Your Session Crashes.*?(?=\n---)',
        text[m_start.start():],
        re.MULTILINE | re.DOTALL
    )
    if not m_end:
        return None, "Could not find '## If Your Session Crashes' section in kit CLAUDE.md"

    block = text[m_start.start(): m_start.start() + m_end.end()]
    return block, None


def detect_commands_heading(text):
    """
    Return (heading, fallback_label) for the first recognized commands heading found.
    fallback_label is None when the standard heading is found (no note needed).
    Returns (None, error_string) when nothing matches.
    """
    for heading, fallback_label in _KNOWN_START_HEADINGS:
        if re.search(r'^' + re.escape(heading), text, re.MULTILINE):
            return heading, fallback_label
    tried = [h for h, _ in _KNOWN_START_HEADINGS]
    return None, f"Could not find a commands section. Tried: {', '.join(tried)}\nIs this a kit project?"


def apply_to_project(project_text, kit_block):
    """
    Replace the kit block in the project CLAUDE.md with the updated kit block.

    Supports '## Session Commands' (standard) and recognized alternatives.
    For the end boundary, tries '## If Your Session Crashes' first, then falls
    back to the next '---' separator — with a clear note when falling back.

    Preserves everything before the commands heading and after the block.
    """
    # ── Find start heading ──
    m_start       = None
    fallback_label = None
    for heading, label in _KNOWN_START_HEADINGS:
        m = re.search(r'^' + re.escape(heading), project_text, re.MULTILINE)
        if m:
            m_start        = m
            fallback_label = label
            break

    if m_start is None:
        tried = [h for h, _ in _KNOWN_START_HEADINGS]
        return None, (
            f"Could not find a commands section. Tried: {', '.join(tried)}\n"
            f"Is this a kit project?"
        )

    after_start = project_text[m_start.start():]

    # ── Find end boundary ──
    m_end = re.search(
        r'^## If Your Session Crashes.*?(?=\n---)',
        after_start,
        re.MULTILINE | re.DOTALL,
    )

    if m_end:
        end_pos = m_start.start() + m_end.end()
    else:
        # Fall back: stop at the next --- separator
        m_sep = re.search(r'\n---', after_start)
        if not m_sep:
            return None, (
                "Could not find an end boundary for the commands section in your CLAUDE.md.\n"
                "Expected '## If Your Session Crashes' or a '---' separator after the commands block."
            )
        end_pos = m_start.start() + m_sep.start()
        if fallback_label:
            print(
                f"  '## If Your Session Crashes' not found — replacing up to the next '---' separator."
            )

    updated = project_text[:m_start.start()] + kit_block + project_text[end_pos:]
    return updated, None


def _read_local_version():
    """Read VERSION from the current project directory, if it exists."""
    p = ROOT / "VERSION"
    if p.exists():
        return p.read_text(encoding="utf-8").strip()
    return None


def migrate_old_refs():
    """Silently rewrite old repo references to the new clankbrain name."""
    old_patterns = [
        ("YehudaFrankel/claude-recall",              "YehudaFrankel/clankbrain"),
        ("YehudaFrankel/Claude-Code-memory-starter-kit", "YehudaFrankel/clankbrain"),
        ("YehudaFrankel/engram",                     "YehudaFrankel/clankbrain"),
    ]
    files_to_check = ["CLAUDE.md", "update.py", "setup.py", "install.py", "upgrade.py"]
    migrated = []
    for fname in files_to_check:
        p = ROOT / fname
        if not p.exists():
            continue
        text = p.read_text(encoding="utf-8")
        updated = text
        for old, new in old_patterns:
            updated = updated.replace(old, new)
        if updated != text:
            p.write_text(updated, encoding="utf-8")
            migrated.append(fname)
    if migrated:
        print(f"  Migrated repo references to clankbrain in: {', '.join(migrated)}")


def main():
    arg = sys.argv[1] if len(sys.argv) > 1 else None

    # Determine source and github_base
    github_base = None
    if arg is None:
        source       = "github"
        source_label = f"GitHub — {DEFAULT_GITHUB_BASE}"
    elif arg.startswith("https://github.com/"):
        raw_base, err = github_url_to_raw_base(arg)
        if err:
            print(f"\nERROR: {err}")
            sys.exit(1)
        source       = "github"
        github_base  = raw_base
        source_label = f"GitHub — {raw_base}"
    else:
        source       = arg
        source_label = f"Local — {arg}"

    print("\n=== Claude Code Kit Updater ===\n")
    print(f"Source: {source_label}")

    # ── Migrate old repo references (claude-recall / Claude-Code-memory-starter-kit → clankbrain) ──
    migrate_old_refs()

    # ── Fetch kit files ──
    print("\nFetching kit files...")
    kit_claude   = get_content(source, "CLAUDE.md",             github_base)
    kit_setup    = get_content(source, "setup.py",              github_base)
    kit_check    = get_content(source, "tools/check_memory.py", github_base)
    kit_memory   = get_content(source, "tools/memory.py",       github_base)
    kit_version  = get_content(source, "VERSION",               github_base)

    if not all([kit_claude, kit_setup, kit_check, kit_memory]):
        print("\nAborted — could not load all kit files.")
        sys.exit(1)

    print("  OK")

    # ── Version check ──
    local_version  = _read_local_version()
    remote_version = kit_version.strip() if kit_version else None

    if local_version and remote_version:
        if local_version == remote_version:
            print(f"\nAlready on v{local_version} — no update needed.")
            sys.exit(0)
        else:
            print(f"\nUpdating from v{local_version} → v{remote_version}")
    elif remote_version:
        print(f"\nInstalling v{remote_version}")
    else:
        print("\nVersion info unavailable — proceeding with update")

    # ── Extract kit block ──
    kit_block, err = extract_kit_block(kit_claude)
    if err:
        print(f"\nERROR: {err}")
        sys.exit(1)

    # ── Load project CLAUDE.md ──
    project_claude_path = ROOT / "CLAUDE.md"
    if not project_claude_path.exists():
        print("\nERROR: No CLAUDE.md found. Run this from your project root.")
        sys.exit(1)

    project_text = project_claude_path.read_text(encoding="utf-8")

    # ── Detect which heading style this project uses ──
    detected_heading, fallback_label = detect_commands_heading(project_text)
    if detected_heading is None:
        print(f"\nERROR: {fallback_label}")
        sys.exit(1)

    # ── Preview ──
    print("\nFiles that will be updated:")
    if fallback_label is not None:
        print(f"  CLAUDE.md             — '{fallback_label}' block -> replaced with '## Session Commands'")
        print(f"                          (your project config below that section is safe)")
    else:
        print("  CLAUDE.md             — session commands block only (your project config is safe)")
    print("  setup.py              — full replacement")
    print("  tools/memory.py       — full replacement (hooks depend on this file)")
    print("  tools/check_memory.py — full replacement")
    print("\nFiles that will NOT be touched:")
    print("  .claude/memory/       — all your memory files")
    print("  STATUS.md             — your session log")
    print("  Everything below '## What This Project Is' in CLAUDE.md")

    if fallback_label is not None:
        print(f"\n  Note: Using '{fallback_label}' as the commands block (non-standard heading detected).")
        print(f"  After this update, your commands section will be headed '## Session Commands'.")


    confirm = input("\nApply update? [y/N] ").strip().lower()
    if confirm != "y":
        print("Cancelled — nothing was changed.")
        sys.exit(0)

    # ── Apply ──
    updated_claude, err = apply_to_project(project_text, kit_block)
    if err:
        print(f"\nERROR: {err}")
        sys.exit(1)

    project_claude_path.write_text(updated_claude, encoding="utf-8")
    (ROOT / "setup.py").write_text(kit_setup, encoding="utf-8")
    tools_dir = ROOT / "tools"
    tools_dir.mkdir(exist_ok=True)
    (tools_dir / "check_memory.py").write_text(kit_check, encoding="utf-8")
    if kit_memory:
        (tools_dir / "memory.py").write_text(kit_memory, encoding="utf-8")

    # Fix hooks in settings.json to use the correct Python binary (python vs python3)
    settings_path = ROOT / ".claude" / "settings.json"
    if settings_path.exists():
        python_bin = _detect_python_bin()
        settings_text = settings_path.read_text(encoding="utf-8")
        # Replace both `python ` and `python3 ` with the detected binary
        fixed = re.sub(r'\bpython3?\b(?= tools/memory\.py)', python_bin, settings_text)
        if fixed != settings_text:
            settings_path.write_text(fixed, encoding="utf-8")
            print(f"  Fixed hooks in .claude/settings.json → using '{python_bin}'")

    # Write VERSION file so future runs can detect "already up to date"
    if remote_version:
        (ROOT / "VERSION").write_text(remote_version + "\n", encoding="utf-8")

    # Save update.py itself so future runs use `python update.py` directly
    kit_updater = get_content(source, "update.py", github_base)
    if kit_updater:
        (ROOT / "update.py").write_text(kit_updater, encoding="utf-8")

    version_note = f" (v{remote_version})" if remote_version else ""
    print(f"\nDone. Kit updated successfully{version_note}.")
    print("  Your memory files, STATUS.md, and project config were not changed.")
    print("  update.py saved — next time just run: python update.py")


if __name__ == "__main__":
    main()
